// Background: Chrome MV3 service worker / Firefox MV3 event page (same bundle for both).
// Message router, Iterable API proxy, key status/test, options-page opener, onboarding, and the
// runtime registration of optional-permission content scripts (frame:'auth' features).
// Contract: docs/ARCHITECTURE.md §4, §6 and §9.
//
// Rules for this file:
//  - No DOM, no `window`: it must run as a service worker.
//  - Listeners are registered synchronously at top level so a woken worker sees the event.
//  - The raw API key only ever goes into the outgoing `Api-Key` header. It is never returned,
//    logged, or put in an error message; response text is scrubbed of it as a last line of defense.
//  - No retries here. Retry policy belongs to the feature (core/retry.js).

import { MSG, API_ERROR, STORAGE } from '../core/messages.js';
import * as settings from '../core/settings.js';
import { FEATURES } from '../features/registry.js';
import { desiredAuthScripts, planScriptSync, featureOrigins, homeFrame } from '../core/feature-frames.js';
import { getKeyForUse, getStatus, recordTest } from '../core/keys.js';
// Legacy-import mappers (features/*/import.js, generated by scripts/build.mjs). Imported directly,
// not via features/optional.js, which would also pull in the DOM-based settings editors.
import importers from 'wb-virtual:importers';
import { runStashedMappers } from '../options/importer/apply.js';
import {
  validateApiRequest, parseRetryAfter, classifySender, senderAllowed, buildOptionsHash,
  parseProjectKey, redactSecret, describeHttpError, describeKeyTest,
} from '../core/api-validation.js';

/** Largest response body relayed back to a content script (Chrome's message cap is 64 MiB). */
const MAX_RESPONSE_BYTES = 32 * 1024 * 1024;
/**
 * Key test endpoint. GET /api/channels is read-only, takes no parameters, returns a few hundred
 * bytes with no PII, and is callable by every server-side key type (full or read-only). Mobile
 * and JavaScript keys are refused, which is the right answer: they can't do Workbench's jobs.
 */
const KEY_TEST_PATH = '/api/channels';
const KEY_TEST_TIMEOUT_MS = 15_000;

// ---------------------------------------------------------------------------
// Response helpers
// ---------------------------------------------------------------------------

function apiFail(code, message, status = 0) {
  return { ok: false, status, error: { code, message } };
}

function safeErrorText(err) {
  // Error messages from fetch/streams never contain request headers, but keep them short.
  return String((err && err.message) || err || 'unknown error').slice(0, 200);
}

class ResponseTooLarge extends Error {}

async function readTextCapped(resp, maxBytes) {
  const declared = Number(resp.headers.get('content-length'));
  if (Number.isFinite(declared) && declared > maxBytes) throw new ResponseTooLarge();
  if (!resp.body || typeof resp.body.getReader !== 'function') {
    const t = await resp.text();
    if (t.length > maxBytes) throw new ResponseTooLarge();
    return t;
  }
  const reader = resp.body.getReader();
  const decoder = new TextDecoder();
  let total = 0;
  let out = '';
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    total += value.byteLength;
    if (total > maxBytes) {
      try { await reader.cancel(); } catch { /* ignore */ }
      throw new ResponseTooLarge();
    }
    out += decoder.decode(value, { stream: true });
  }
  return out + decoder.decode();
}

// Chrome may stop an idle extension service worker, including one waiting more than 30 s for a
// fetch() response. Requests may run for up to 120 s (bulk endpoints), so while any are in flight
// we make a trivial extension API call every 20 s, which resets the idle timer (Chrome 110+).
// Harmless on a Firefox event page.
let inFlight = 0;
let keepAliveTimer = null;

function keepAliveStart() {
  if (inFlight++ > 0) return;
  keepAliveTimer = setInterval(() => {
    try {
      const p = chrome.runtime.getPlatformInfo?.();
      if (p && typeof p.catch === 'function') p.catch(() => {});
    } catch { /* ignore */ }
  }, 20_000);
}

function keepAliveStop() {
  if (--inFlight > 0) return;
  inFlight = 0;
  clearInterval(keepAliveTimer);
  keepAliveTimer = null;
}

/**
 * Perform one validated request. `req` is validateApiRequest(...).value.
 * Always resolves to { ok, status, data?, retryAfterMs?, error? }.
 */
async function performApiRequest(req, apiKey) {
  keepAliveStart();
  try {
    return await doFetch(req, apiKey);
  } finally {
    keepAliveStop();
  }
}

async function doFetch(req, apiKey) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), req.timeoutMs);
  const headers = { 'Api-Key': apiKey, Accept: 'application/json' };
  if (req.bodyJson != null) headers['Content-Type'] = 'application/json';

  try {
    let resp;
    try {
      resp = await globalThis.fetch(req.url, {
        method: req.method,
        headers,
        body: req.bodyJson ?? undefined,
        signal: ctrl.signal,
        credentials: 'omit',        // never attach cookies to api.iterable.com
        redirect: 'error',          // custom headers survive cross-origin redirects; don't follow any
        cache: 'no-store',
        referrerPolicy: 'no-referrer',
      });
    } catch (err) {
      if (ctrl.signal.aborted) return apiFail(API_ERROR.TIMEOUT, `No response within ${Math.round(req.timeoutMs / 1000)}s.`);
      return apiFail(API_ERROR.NETWORK, 'Network error: ' + safeErrorText(err));
    }

    const retryAfterMs = parseRetryAfter(resp.headers.get('retry-after'));
    let text;
    try {
      text = await readTextCapped(resp, MAX_RESPONSE_BYTES);
    } catch (err) {
      // NETWORK / TIMEOUT always carry status 0 (§6), even though a status line arrived: callers
      // tell "outcome unknown" apart by status 0 + code (core/retry.js isOutcomeUnknown), and a
      // 200 whose body never arrived must not look like an HTTP answer.
      if (err instanceof ResponseTooLarge) {
        return apiFail(API_ERROR.NETWORK, `Response larger than ${MAX_RESPONSE_BYTES / 1024 / 1024} MiB; not relayed (HTTP ${resp.status}).`);
      }
      if (ctrl.signal.aborted) return apiFail(API_ERROR.TIMEOUT, `Response not complete within ${Math.round(req.timeoutMs / 1000)}s (HTTP ${resp.status}).`);
      return apiFail(API_ERROR.NETWORK, `Network error while reading the response (HTTP ${resp.status}): ` + safeErrorText(err));
    }

    // Last line of defense: if the server ever echoes the key back, it doesn't leave the background.
    text = redactSecret(text, apiKey);
    let data = null;
    if (text) {
      try { data = JSON.parse(text); } catch { data = text; }
    }

    const out = { ok: resp.ok, status: resp.status, data };
    if (retryAfterMs !== undefined) out.retryAfterMs = retryAfterMs;
    if (!resp.ok) out.error = { code: API_ERROR.HTTP, message: describeHttpError(resp.status, data) };
    return out;
  } finally {
    clearTimeout(timer);
  }
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

async function handleApi(msg) {
  const v = validateApiRequest(msg);
  if (!v.ok) return apiFail(API_ERROR.BAD_REQUEST, v.message);
  const entry = await getKeyForUse(v.value.projectKey);
  if (!entry) return apiFail(API_ERROR.NO_KEY, 'No API key saved for this project. Add one in Workbench settings.');
  // The host comes from the projectKey; the stored entry must agree (keys.js enforces this on write).
  if (entry.dataCenter !== v.value.dataCenter) return apiFail(API_ERROR.NO_KEY, 'Saved key does not match this project\u2019s data center.');
  return performApiRequest(v.value, entry.apiKey);
}

async function handleKeysStatus(msg) {
  const s = await getStatus(msg.projectKey);
  return { hasKey: s.hasKey, masked: s.masked, name: s.name };
}

/** Transient outcomes (network, timeout, 429, 5xx) say nothing about the key, so they aren't recorded. */
function isDefinitiveTest(res) {
  if (!res.error) return true;
  if (res.error.code !== API_ERROR.HTTP) return false;
  return res.status >= 400 && res.status < 500 && res.status !== 429;
}

async function handleKeysTest(msg) {
  const pk = parseProjectKey(msg.projectKey);
  if (!pk) return { ok: false, status: 0, message: 'Project key is malformed.' };
  const entry = await getKeyForUse(msg.projectKey);
  if (!entry) return { ok: false, status: 0, message: describeKeyTest({ ok: false, errorCode: API_ERROR.NO_KEY }) };
  const v = validateApiRequest({ projectKey: msg.projectKey, method: 'GET', path: KEY_TEST_PATH, timeoutMs: KEY_TEST_TIMEOUT_MS });
  if (!v.ok) return { ok: false, status: 0, message: 'Internal error building the test request.' };
  const res = await performApiRequest(v.value, entry.apiKey);
  const message = describeKeyTest({
    ok: res.ok, status: res.status, errorCode: res.error && res.error.code, dataCenter: pk.dataCenter,
  });
  if (isDefinitiveTest(res)) {
    try {
      await recordTest(msg.projectKey, { ok: res.ok, status: res.status, savedAt: entry.savedAt });
    } catch { /* result is still reported to the caller */ }
  }
  return { ok: res.ok, status: res.status, message };
}

async function findOptionsTab(baseUrl) {
  // Chrome 116+: runtime.getContexts sees our own pages without the "tabs" permission.
  if (typeof chrome.runtime.getContexts === 'function') {
    try {
      const ctxs = await chrome.runtime.getContexts({ contextTypes: ['TAB'] });
      const hit = ctxs.find((c) => typeof c.documentUrl === 'string' && c.documentUrl.split('#')[0] === baseUrl && c.tabId >= 0);
      if (hit) return { tabId: hit.tabId, windowId: hit.windowId };
      return null;
    } catch { /* fall through */ }
  }
  // Firefox: tab.url is only visible where the browser lets us see it; otherwise we open a new tab.
  try {
    const tabs = await chrome.tabs.query({});
    const hit = tabs.find((t) => typeof t.url === 'string' && t.url.split('#')[0] === baseUrl);
    if (hit) return { tabId: hit.id, windowId: hit.windowId };
  } catch { /* ignore */ }
  return null;
}

async function handleOpenOptions(msg) {
  const hash = buildOptionsHash(msg.section, msg.params);
  if (hash === null) return { ok: false, error: { code: API_ERROR.BAD_REQUEST, message: 'Invalid settings section or parameters.' } };

  const base = chrome.runtime.getURL('options.html');
  const target = base + hash;
  const existing = await findOptionsTab(base);
  if (existing) {
    await chrome.tabs.update(existing.tabId, hash ? { active: true, url: target } : { active: true });
    if (existing.windowId != null && chrome.windows?.update) {
      try { await chrome.windows.update(existing.windowId, { focused: true }); } catch { /* ignore */ }
    }
  } else {
    await chrome.tabs.create({ url: target });
  }
  return { ok: true };
}

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

const HANDLERS = {
  [MSG.API]: handleApi,
  [MSG.KEYS_STATUS]: handleKeysStatus,
  [MSG.KEYS_TEST]: handleKeysTest,
  [MSG.OPEN_OPTIONS]: handleOpenOptions,
};

/** The response a type returns when its handler can't run, in that type's own shape. */
function failureFor(type, code, message) {
  switch (type) {
    case MSG.API: return apiFail(code, message);
    case MSG.KEYS_STATUS: return { hasKey: false, masked: '', name: '', error: { code, message } };
    case MSG.KEYS_TEST: return { ok: false, status: 0, message };
    default: return { ok: false, error: { code, message } };
  }
}

function onMessage(msg, sender, sendResponse) {
  if (!msg || typeof msg !== 'object' || typeof msg.type !== 'string') return false;
  if (!Object.hasOwn(HANDLERS, msg.type)) return false; // not ours (or popup→content traffic)

  const kind = classifySender(sender, {
    runtimeId: chrome.runtime.id,
    extensionBaseUrl: chrome.runtime.getURL(''),
  });
  if (!kind) return false; // unknown sender: ignore silently
  if (!senderAllowed(msg.type, kind)) {
    sendResponse(failureFor(msg.type, API_ERROR.BAD_REQUEST, 'This request is not allowed from here.'));
    return false;
  }

  // `return true` + sendResponse works in both Chrome and Firefox MV3 (Chrome only recently
  // learned to accept a returned Promise).
  Promise.resolve()
    .then(() => HANDLERS[msg.type](msg, sender, kind))
    .then(
      (res) => sendResponse(res),
      (err) => {
        // Messages from keys.js / fetch never contain the key; still don't log request details.
        console.warn('[WB:bg]', msg.type, 'failed:', err && err.name, safeErrorText(err));
        sendResponse(failureFor(msg.type, API_ERROR.NETWORK, 'Workbench background error: ' + safeErrorText(err)));
      },
    );
  return true;
}

function onInstalled(details) {
  if (details && details.reason === 'install') {
    chrome.tabs.create({ url: chrome.runtime.getURL('options.html#welcome') }).catch(() => {});
  }
  // A new version may ship mappers for scripts whose settings were stashed at import time
  // (wb:legacy:*, ARCHITECTURE §8.4). The options page also runs this on every load.
  if (details && details.reason === 'update') {
    runStashedMappers(importers, { announced: false }).then(
      (done) => { if (done.length) console.info('[WB:bg] imported stashed settings for', done.map((d) => d.featureId).join(', ')); },
      (err) => console.warn('[WB:bg] stashed-settings import failed:', safeErrorText(err)),
    );
  }
}

// ---------------------------------------------------------------------------
// Optional-permission content scripts (frame:'auth')
// ---------------------------------------------------------------------------
//
// content-auth.js is registered at runtime for exactly (enabled frame:'auth' features ∩ granted
// optional origins), never listed in the static manifest (that would make the host required).
// Re-synced on every background start (a service worker / event page wakes often; the diff makes
// that cheap and idempotent) and whenever settings or permissions change. Registrations use
// persistAcrossSessions, but nothing relies on it: a browser that drops them (or keeps a stale
// one) is corrected by the next start.

let syncChain = Promise.resolve();
let syncQueued = false;

function scheduleScriptSync(reason) {
  if (syncQueued) return syncChain;
  syncQueued = true;
  syncChain = syncChain
    .then(() => { syncQueued = false; return syncOptionalScripts(); })
    .then(
      (plan) => { if (plan && (plan.unregister.length || plan.register.length)) console.info('[WB:bg] content scripts synced (' + reason + '):', JSON.stringify(plan.register.map((s) => ({ id: s.id, matches: s.matches }))), 'removed', JSON.stringify(plan.unregister)); },
      (err) => console.warn('[WB:bg] content script sync failed (' + reason + '):', safeErrorText(err)),
    );
  return syncChain;
}

async function syncOptionalScripts() {
  // Built without any frame:'auth' feature → no "scripting" permission and nothing to register.
  if (!chrome.scripting?.registerContentScripts) return null;
  const metas = FEATURES.filter((m) => homeFrame(m) === 'auth');
  const resolved = await settings.load();
  const granted = new Set();
  for (const origin of new Set(metas.flatMap(featureOrigins))) {
    try { if (await chrome.permissions.contains({ origins: [origin] })) granted.add(origin); } catch { /* not granted */ }
  }
  const desired = desiredAuthScripts({ metas, settings: resolved, granted });
  const current = await chrome.scripting.getRegisteredContentScripts();
  const plan = planScriptSync(current, desired);
  if (plan.unregister.length) await chrome.scripting.unregisterContentScripts({ ids: plan.unregister });
  if (plan.register.length) await chrome.scripting.registerContentScripts(plan.register);
  return plan;
}

function onStorageChanged(changes, areaName) {
  if (areaName === 'local' && changes && Object.hasOwn(changes, STORAGE.SETTINGS)) scheduleScriptSync('settings changed');
}

chrome.runtime.onMessage.addListener(onMessage);
chrome.runtime.onInstalled.addListener(onInstalled);
chrome.storage.onChanged.addListener(onStorageChanged);
chrome.permissions.onAdded.addListener(() => scheduleScriptSync('permission granted'));
chrome.permissions.onRemoved.addListener(() => scheduleScriptSync('permission removed'));
scheduleScriptSync('background start');
