// Content entry for app.iterable.com / app.eu.iterable.com (top frame, isolated world).

import { MSG } from '../core/messages.js';
import * as settings from '../core/settings.js';
import { createProjectTracker } from '../core/project.js';
import { createRouter } from '../core/router.js';
import { createLogger } from '../core/log.js';
import { FEATURES, getMeta } from '../features/registry.js';
// Generated by scripts/build.mjs: features whose meta.frame is 'top' (index.js), plus the top
// companions (top.js) of features homed in another frame.
import IMPLS from 'wb-virtual:impls/top';
import { injectPageFonts } from '../ui/fonts.js';
import { watchGeneralSettings } from '../ui/theme.js';
import { makeContext } from './context.js';
import { announceToBeeFrames } from './embed-handshake.js';
import { createTopHub } from '../core/frames.js';
import { createPageHub } from '../core/page-rpc.js';

const log = createLogger('app');

function start() {
  if (window.__wbAppStarted) return; // guard against double injection after an extension reload
  window.__wbAppStarted = true;

  injectPageFonts();
  watchGeneralSettings();

  const project = createProjectTracker();
  // Frame channel to app.getbee.io editor frames (ARCHITECTURE §6.2) and page-world RPC to the
  // MAIN-world script (main-world.js, §6.3). Both are shared by every feature on this page.
  const frames = createTopHub({ win: window, log });
  frames.start();
  const page = createPageHub({ available: true, log });
  const router = createRouter({
    frame: 'top',
    metas: FEATURES,
    impls: IMPLS,
    makeCtx: (meta, base) => makeContext(meta, base, { project, frame: 'top', frames, page }),
    loadSettings: settings.load,
    subscribeSettings: settings.subscribe,
  });

  project.onChange((next, prev) => log.debug('project', prev?.key, '→', next?.key));
  router.onUrlChange(() => { project.refresh(); });
  project.refresh({ force: true });
  router.start().catch((e) => log.error('router failed to start', e));
  announceToBeeFrames();

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (sender.id !== chrome.runtime.id || !msg || typeof msg !== 'object') return false;

    if (msg.type === MSG.TAB_STATUS) {
      // Make sure the popup sees a project even if the first detection is still in flight.
      const pending = project.current() ? Promise.resolve() : project.refresh({ force: true });
      pending.then(() => sendResponse({ url: location.href, project: project.current(), mounted: router.mounted() }));
      return true;
    }

    if (msg.type === MSG.FEATURE_ACTION) {
      const meta = getMeta(msg.featureId);
      if (!meta || (meta.frame || 'top') !== 'top') return false; // a bee frame may answer
      const ok = router.dispatchAction(msg.featureId, msg.action);
      sendResponse(ok ? { ok: true } : { ok: false, error: { code: 'NOT_MOUNTED', message: `${meta.name} is not active on this page.` } });
      return false;
    }

    if (msg.type === MSG.FEATURE_REQUEST) {
      // From the popup or the background (sender.id checked above; content scripts can't message
      // each other this way). The feature validates its own payload.
      const meta = getMeta(msg.featureId);
      if (!meta || (meta.frame || 'top') !== 'top' || typeof msg.action !== 'string') return false;
      const p = router.requestAction(msg.featureId, msg.action, msg.payload);
      if (!p) {
        sendResponse({ ok: false, error: { code: 'NOT_MOUNTED', message: `${meta.name} is not active on this page.` } });
        return false;
      }
      p.then(
        (result) => sendResponse({ ok: true, result: result ?? null }),
        (e) => sendResponse({ ok: false, error: { code: 'FAILED', message: String(e?.message || e).slice(0, 200) } }),
      );
      return true;
    }
    return false;
  });
}

start();
