// Content entry for optional-permission sign-in pages (frame:'auth', e.g. auth.iterable.com).
//
// NOT listed in the manifest's static content_scripts: that would make the host a required
// permission. The background registers this file with chrome.scripting.registerContentScripts
// only for the origins of enabled frame:'auth' features the user has granted (ARCHITECTURE §4,
// §9), and re-syncs that registration on every start.
//
// Least privilege: no project detection, no API access (the background accepts only
// wb:open-options from these pages), no frame channel, no page-world script, no web fonts (the
// fonts aren't web-accessible to this host; the fallback stack applies).

import { MSG } from '../core/messages.js';
import * as settings from '../core/settings.js';
import { createRouter } from '../core/router.js';
import { createLogger } from '../core/log.js';
import { FEATURES, getMeta } from '../features/registry.js';
import { featureMatchesOrigin } from '../core/feature-frames.js';
// Generated by scripts/build.mjs: only the features whose meta.frame is 'auth'.
import IMPLS from 'wb-virtual:impls/auth';
import { watchGeneralSettings } from '../ui/theme.js';
import { makeContext } from './context.js';

const log = createLogger('auth');

function start() {
  if (window.__wbAuthStarted) return;
  window.__wbAuthStarted = true;
  if (window.top !== window) return; // registered with allFrames: false; belt and braces

  // Only features that declared this origin (a registration covers the union of several
  // features' origins; each feature runs only on its own).
  const metas = FEATURES.filter((m) => (m.frame || 'top') === 'auth' && featureMatchesOrigin(m, location.origin));
  if (!metas.length) return;

  watchGeneralSettings();
  const router = createRouter({
    frame: 'auth',
    metas,
    impls: IMPLS,
    makeCtx: (meta, base) => makeContext(meta, base, { project: null, frame: 'auth' }),
    loadSettings: settings.load,
    subscribeSettings: settings.subscribe,
  });
  router.start().catch((e) => log.error('router failed to start', e));

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (sender.id !== chrome.runtime.id || msg?.type !== MSG.FEATURE_ACTION) return false;
    const meta = getMeta(msg.featureId);
    if (!meta || meta.frame !== 'auth') return false;
    if (!router.dispatchAction(msg.featureId, msg.action)) return false;
    sendResponse({ ok: true });
    return false;
  });
}

start();
