// MAIN-world entry for the Iterable app pages (document_start). Two jobs:
//  1. Tell the isolated world when the SPA changes the URL: isolated scripts can't see the page's
//     history.pushState / replaceState calls.
//  2. Host the page-world RPC handlers of features that ship a main.js (page/rpc-host.js,
//     ARCHITECTURE §6.3), so their isolated code can drive page objects (e.g. the Ace editor).
// This runs as page script: no extension APIs, no secrets, and everything it does page script could
// do too. Keep it small.

import { emit, BRIDGE } from '../core/bridge.js';
import { startRpcHost } from './rpc-host.js';
// Generated by scripts/build.mjs: { [featureId]: main.js } for top-frame features with a main.js.
import MAIN_HANDLERS from 'wb-virtual:main/top';

for (const method of ['pushState', 'replaceState']) {
  const original = history[method];
  history[method] = function (...args) {
    const result = original.apply(this, args);
    try { emit(BRIDGE.LOCATION, { method }); } catch { /* never break the page */ }
    return result;
  };
}

try { startRpcHost(MAIN_HANDLERS); } catch (e) { console.error('[WB:page] RPC host failed to start', e); }
